[package]
name = "sched"
version = "0.1.0"
authors = ["Tuyen <michael.ross.mckay@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]